version: '3'
services:
  lb:
      image: haproxy
      ports:
          - "8080:8080"
      volumes:
          - ./haproxy:/usr/local/etc/haproxy
  nodecontroller1:
      image: nodecontroller
      environment:
          - APPID=1111
  nodecontroller2:
      image: nodecontroller
      environment:
          - APPID=2222  
  client:
    build: './client'
    ports:
      - "3000:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
      - PORT=3000

  restaurateur:
    build: './restaurateur'
    ports:
      - "3001:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
      - PORT=3000

  livreur:
    build: './livreur'
    ports:
      - "3002:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
      - PORT=3000

  commercial:
    build: './commercial'
    ports:
      - "3003:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
      - PORT=3000

  technique:
    build: './technique'
    ports:
      - "3004:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/microservices
      - PORT=3000
  
  db:
    image: mongo
    ports:
      - "27017:27017"
